function [summaryTable, perImageTable] = ...
        evaluate_minimal_sliding_unet(modelFile)
%EVALUATE_MINIMAL_SLIDING_UNET 在完整 test 图像上执行滑窗评估。

    thisDir = fileparts(mfilename('fullpath'));
    repoRoot = fileparts(fileparts(thisDir));

    if nargin < 1 || isempty(modelFile)
        modelFile = fullfile( ...
            repoRoot, 'models', ...
            'crack500_unet_minimal_sliding_256.mat');
    end

    if ~isfile(modelFile)
        error('Model not found: %s', modelFile);
    end

    S = load(modelFile, 'net', 'trainingConfig');
    net = S.net;
    config = S.trainingConfig;

    testDir = fullfile( ...
        repoRoot, 'src', 'data', ...
        'CRACK500', 'test');

    resultDir = fullfile( ...
        repoRoot, 'results', 'deeplearning', ...
        'minimal_sliding_256', 'test');

    maskDir = fullfile(resultDir, 'predicted_masks');
    overlayDir = fullfile(resultDir, 'overlays');

    createFolder(resultDir);
    createFolder(maskDir);
    createFolder(overlayDir);

    pairTable = list_samebasename_pairs(testDir);
    validate_pair_table(pairTable);

    numberOfImages = height(pairTable);

    precision = zeros(numberOfImages,1);
    recall = zeros(numberOfImages,1);
    f1 = zeros(numberOfImages,1);
    crackIoU = zeros(numberOfImages,1);
    backgroundIoU = zeros(numberOfImages,1);
    meanIoU = zeros(numberOfImages,1);

    predictedCrackRatio = zeros(numberOfImages,1);
    groundTruthCrackRatio = zeros(numberOfImages,1);

    totalSeconds = zeros(numberOfImages,1);
    networkSeconds = zeros(numberOfImages,1);
    numberOfTiles = zeros(numberOfImages,1);

    TP = zeros(numberOfImages,1);
    FP = zeros(numberOfImages,1);
    FN = zeros(numberOfImages,1);
    TN = zeros(numberOfImages,1);

    % 网络预热一个 tile。
    Iwarm = imread(char(pairTable.ImageFile(1)));
    [warmTiles, ~] = extract_minimal_sliding_tiles( ...
        Iwarm, config.windowSize, config.stride);

    warmLabels = semanticseg( ...
        im2single(warmTiles(:,:,:,1)), net);
    clear warmLabels;

    fprintf('\n===== Sliding-window test evaluation =====\n');

    for imageIndex = 1:numberOfImages
        I = imread(char(pairTable.ImageFile(imageIndex)));

        Mraw = imread(char(pairTable.MaskFile(imageIndex)));
        if ndims(Mraw) == 3
            Mraw = Mraw(:,:,1);
        end
        groundTruth = Mraw > 0;

        [predictedMask, ~, predictionInfo] = ...
            predict_minimal_sliding_unet( ...
                I, net, config.bestThreshold, ...
                config.windowSize, ...
                config.stride, ...
                config.blendMode);

        metrics = compute_minimal_segmentation_metrics( ...
            predictedMask, groundTruth);

        precision(imageIndex) = metrics.Precision;
        recall(imageIndex) = metrics.Recall;
        f1(imageIndex) = metrics.F1;
        crackIoU(imageIndex) = metrics.CrackIoU;
        backgroundIoU(imageIndex) = metrics.BackgroundIoU;
        meanIoU(imageIndex) = metrics.MeanIoU;

        TP(imageIndex) = metrics.TP;
        FP(imageIndex) = metrics.FP;
        FN(imageIndex) = metrics.FN;
        TN(imageIndex) = metrics.TN;

        predictedCrackRatio(imageIndex) = ...
            nnz(predictedMask) / numel(predictedMask);

        groundTruthCrackRatio(imageIndex) = ...
            nnz(groundTruth) / numel(groundTruth);

        totalSeconds(imageIndex) = ...
            predictionInfo.TotalSeconds;

        networkSeconds(imageIndex) = ...
            predictionInfo.NetworkSeconds;

        numberOfTiles(imageIndex) = ...
            predictionInfo.NumberOfTiles;

        [~, baseName, ~] = ...
            fileparts(char(pairTable.ImageFile(imageIndex)));

        imwrite(uint8(predictedMask)*255, ...
            fullfile(maskDir, ...
                [baseName '_minimal_sliding_mask.png']));

        overlay = labeloverlay( ...
            I, predictedMask, ...
            'Transparency', 0.65, ...
            'Colormap', [0 1 0]);

        imwrite(overlay, ...
            fullfile(overlayDir, ...
                [baseName '_minimal_sliding_overlay.png']));

        fprintf('Processed %d / %d\r', ...
            imageIndex, numberOfImages);
    end

    fprintf('\n');

    pooledTP = sum(TP);
    pooledFP = sum(FP);
    pooledFN = sum(FN);

    microPrecision = pooledTP / ...
        max(pooledTP + pooledFP, 1);

    microRecall = pooledTP / ...
        max(pooledTP + pooledFN, 1);

    microF1 = 2*microPrecision*microRecall / ...
        max(microPrecision + microRecall, eps);

    microCrackIoU = pooledTP / ...
        max(pooledTP + pooledFP + pooledFN, 1);

    imagesPerSecond = ...
        numberOfImages / sum(totalSeconds);

    tilesPerSecond = ...
        sum(numberOfTiles) / sum(networkSeconds);

    perImageTable = table( ...
        pairTable.ImageFile, ...
        precision, recall, f1, ...
        crackIoU, backgroundIoU, meanIoU, ...
        predictedCrackRatio, ...
        groundTruthCrackRatio, ...
        numberOfTiles, ...
        networkSeconds, totalSeconds, ...
        TP, FP, FN, TN, ...
        'VariableNames', { ...
            'ImageFile', ...
            'Precision', 'Recall', 'F1', ...
            'CrackIoU', 'BackgroundIoU', 'MeanIoU', ...
            'PredictedCrackRatio', ...
            'GroundTruthCrackRatio', ...
            'NumberOfTiles', ...
            'NetworkSeconds', ...
            'TotalSeconds', ...
            'TP', 'FP', 'FN', 'TN'});

    summaryTable = table( ...
        mean(precision), ...
        mean(recall), ...
        mean(f1), ...
        mean(crackIoU), ...
        mean(meanIoU), ...
        microPrecision, ...
        microRecall, ...
        microF1, ...
        microCrackIoU, ...
        mean(predictedCrackRatio), ...
        mean(groundTruthCrackRatio), ...
        sum(f1 == 0), ...
        config.bestThreshold, ...
        imagesPerSecond, ...
        tilesPerSecond, ...
        mean(numberOfTiles), ...
        'VariableNames', { ...
            'MacroPrecision', ...
            'MacroRecall', ...
            'MacroF1', ...
            'MacroCrackIoU', ...
            'MacroMeanIoU', ...
            'MicroPrecision', ...
            'MicroRecall', ...
            'MicroF1', ...
            'MicroCrackIoU', ...
            'PredictedCrackRatio', ...
            'GroundTruthCrackRatio', ...
            'ZeroF1Images', ...
            'Threshold', ...
            'ImagesPerSecond', ...
            'TilesPerSecond', ...
            'AverageTilesPerImage'}, ...
        'RowNames', {'MinimalSlidingUNet'});

    disp(summaryTable);

    writetable(perImageTable, ...
        fullfile(resultDir, ...
            'per_image_metrics.csv'));

    writetable(summaryTable, ...
        fullfile(resultDir, ...
            'summary_metrics.csv'), ...
        'WriteRowNames', true);
end

function createFolder(folderPath)
    if ~isfolder(folderPath)
        mkdir(folderPath);
    end
end
