function [bestThreshold, thresholdTable] = ...
        tune_minimal_sliding_threshold( ...
            net, validationDir, ...
            windowSize, stride, blendMode, ...
            thresholdCandidates)
%TUNE_MINIMAL_SLIDING_THRESHOLD 在完整 validation 图像上选择阈值。
%
% 每张 validation 图只推理一次，然后测试多个 threshold。
% test set 不参与 threshold 选择。

    pairTable = list_samebasename_pairs(validationDir);
    validate_pair_table(pairTable);

    numberOfImages = height(pairTable);
    numberOfThresholds = numel(thresholdCandidates);

    macroPrecisionSum = zeros(numberOfThresholds,1);
    macroRecallSum = zeros(numberOfThresholds,1);
    macroF1Sum = zeros(numberOfThresholds,1);
    macroIoUSum = zeros(numberOfThresholds,1);

    pooledTP = zeros(numberOfThresholds,1);
    pooledFP = zeros(numberOfThresholds,1);
    pooledFN = zeros(numberOfThresholds,1);

    fprintf('\nSearching threshold on full validation images...\n');

    for imageIndex = 1:numberOfImages
        I = imread(char(pairTable.ImageFile(imageIndex)));

        Mraw = imread(char(pairTable.MaskFile(imageIndex)));
        if ndims(Mraw) == 3
            Mraw = Mraw(:,:,1);
        end
        groundTruth = Mraw > 0;

        [~, scoreMap] = predict_minimal_sliding_unet( ...
            I, net, 0.5, ...
            windowSize, stride, blendMode);

        for thresholdIndex = 1:numberOfThresholds
            predictedMask = ...
                scoreMap >= thresholdCandidates(thresholdIndex);

            metrics = ...
                compute_minimal_segmentation_metrics( ...
                    predictedMask, groundTruth);

            macroPrecisionSum(thresholdIndex) = ...
                macroPrecisionSum(thresholdIndex) + ...
                metrics.Precision;

            macroRecallSum(thresholdIndex) = ...
                macroRecallSum(thresholdIndex) + ...
                metrics.Recall;

            macroF1Sum(thresholdIndex) = ...
                macroF1Sum(thresholdIndex) + ...
                metrics.F1;

            macroIoUSum(thresholdIndex) = ...
                macroIoUSum(thresholdIndex) + ...
                metrics.CrackIoU;

            pooledTP(thresholdIndex) = ...
                pooledTP(thresholdIndex) + metrics.TP;

            pooledFP(thresholdIndex) = ...
                pooledFP(thresholdIndex) + metrics.FP;

            pooledFN(thresholdIndex) = ...
                pooledFN(thresholdIndex) + metrics.FN;
        end

        fprintf('Threshold tuning %d / %d\r', ...
            imageIndex, numberOfImages);
    end

    fprintf('\n');

    macroPrecision = macroPrecisionSum / numberOfImages;
    macroRecall = macroRecallSum / numberOfImages;
    macroF1 = macroF1Sum / numberOfImages;
    macroCrackIoU = macroIoUSum / numberOfImages;

    microPrecision = pooledTP ./ ...
        max(pooledTP + pooledFP, 1);

    microRecall = pooledTP ./ ...
        max(pooledTP + pooledFN, 1);

    microF1 = 2*microPrecision.*microRecall ./ ...
        max(microPrecision + microRecall, eps);

    microCrackIoU = pooledTP ./ ...
        max(pooledTP + pooledFP + pooledFN, 1);

    thresholdTable = table( ...
        thresholdCandidates(:), ...
        macroPrecision, macroRecall, ...
        macroF1, macroCrackIoU, ...
        microPrecision, microRecall, ...
        microF1, microCrackIoU, ...
        'VariableNames', { ...
            'Threshold', ...
            'MacroPrecision', ...
            'MacroRecall', ...
            'MacroF1', ...
            'MacroCrackIoU', ...
            'MicroPrecision', ...
            'MicroRecall', ...
            'MicroF1', ...
            'MicroCrackIoU'});

    rankingTable = sortrows( ...
        thresholdTable, ...
        {'MacroF1','MacroCrackIoU'}, ...
        {'descend','descend'});

    bestThreshold = rankingTable.Threshold(1);

    fprintf('Best validation threshold: %.2f\n', ...
        bestThreshold);

    disp(rankingTable( ...
        1:min(5,height(rankingTable)), :));
end
